FROM node:6

ENV DOCKER 1

RUN apt-get update && \
    apt-get install -y rsync python

ADD package.json /src/package.json
WORKDIR /src

RUN npm set registry https://registry.npmjs.org
RUN npm install
RUN npm install -g nodemon
